# Generated by Django 3.2.4 on 2021-06-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('opening_text', models.TextField(max_length=2000)),
                ('director_name', models.CharField(max_length=250, unique=True)),
                ('characters', models.ManyToManyField(to='characters.Character')),
                ('planets', models.ManyToManyField(to='characters.Planet')),
            ],
        ),
    ]
